# Name of the GitHub Actions workflow
name: Build Tauri App (Linux)

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main # Or your default branch, e.g., master
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches:
      - main # Or your default branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-linux"
  build-linux:
    # The name that will be displayed on GitHub for this job
    name: Build for Linux
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version your project uses or a recent LTS

      # Step 3: Install the stable Rust toolchain
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable # Explicitly set to stable, though it's the default

      # Step 4: Install necessary Linux dependencies for Tauri (and webkit2gtk for the webview)
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # Step 5: Install frontend dependencies using npm
      # This assumes your package.json and package-lock.json are in the 'torn-status-widget' directory
      - name: Install frontend dependencies
        working-directory: ./torn-status-widget # Set working directory for npm commands
        run: npm install

      # Step 6: Use the official Tauri action to build the application
      # This action handles installing Tauri CLI, building the frontend, and then building the Tauri app.
      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0 # Using v0 for the latest release of the action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }} # Uncomment if using Tauri's updater and code signing
          # TAURI_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }} # Uncomment if your private key is password-protected
        with:
          # Path to the directory containing your tauri.conf.json and package.json for the widget
          projectPath: './torn-status-widget'
          # Explicitly tell the action how to run the tauri CLI using npx.
          # npx will find and execute tauri from the local node_modules (installed in step 5)
          # or fetch it if not found locally.
          tauriScript: 'npx tauri'
          # The tauri-action will automatically build for the runner's OS (Linux)
          # and produce .deb and .AppImage by default.
          # You can specify targets: 'deb,appimage' if you want to be explicit.

          # If you want the action to create a GitHub Release with the artifacts:
          # tagName: app-v__VERSION__ # __VERSION__ is auto-replaced with app version from tauri.conf.json
          # releaseName: 'App v__VERSION__'
          # releaseBody: 'See the assets to download this version of the Torn Status Widget.'
          # releaseDraft: false # Set to true to create a draft release
          # releasePrerelease: false # Set to true if this is a pre-release

      # Step 7: Upload the built Linux artifacts (.deb and .AppImage)
      # This step is useful if you are not using the release creation feature of tauri-action directly,
      # or if you want to access the artifacts for other purposes before a release.
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: torn-status-widget-linux-builds # Name of the artifact bundle
          path: |
            ./torn-status-widget/src-tauri/target/release/bundle/deb/*.deb
            ./torn-status-widget/src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: error # Fails the step if no files are found at the specified paths
